using System.Text.Json;
using HookLab.Watcher.Companion;
using Xunit;

namespace HookLab.Watcher.Companion.Tests;
public sealed class CompanionTests {
	[Theory]
	[InlineData("running",true,false,null,CompanionState.Running)] [InlineData("running",true,true,null,CompanionState.Paused)] [InlineData("running",false,false,null,CompanionState.Stale)] [InlineData("stopped",false,false,null,CompanionState.Stopped)] [InlineData("running",true,false,"broken catalog",CompanionState.Error)]
	public void Status_is_classified_honestly(string lifecycle,bool alive,bool paused,string? error,CompanionState expected) { using var directory=new TemporaryDirectory(); File.WriteAllText(Path.Combine(directory.Path,"watcher-status.json"),JsonSerializer.Serialize(new { schemaVersion=1,watcherProcessId=123,watcherProcessCreationUtcTicks=456,lifecycle,paused,disabledProfiles=new[]{"beta"},catalogError=error,definitions=new[]{new { profileId="alpha" },new { profileId="beta" }} })); var snapshot=CompanionSnapshot.Read(new(directory.Path,Path.Combine(directory.Path,"audit.jsonl")),alive?(_,_)=>true:(_,_)=>false); Assert.Equal(expected,snapshot.State); Assert.Equal(new[]{"alpha","beta"},snapshot.Profiles); Assert.Contains("beta",snapshot.DisabledProfiles); }
	[Fact] public void Missing_status_is_stopped_and_malformed_status_is_error() { using var directory=new TemporaryDirectory(); var paths=new CompanionPaths(directory.Path,Path.Combine(directory.Path,"audit.jsonl")); Assert.Equal(CompanionState.Stopped,CompanionSnapshot.Read(paths).State); File.WriteAllText(Path.Combine(directory.Path,"watcher-status.json"),"{"); Assert.Equal(CompanionState.Error,CompanionSnapshot.Read(paths).State); }
	[Fact] public void Pause_resume_and_profile_toggles_share_the_watcher_control_contract() { using var directory=new TemporaryDirectory(); var operations=new CompanionOperations(new(directory.Path,Path.Combine(directory.Path,"audit.jsonl"))); operations.Pause(true); operations.SetProfile("alpha",false); var control=new HookLab.Watcher.WatchControlStore(Path.Combine(directory.Path,"watcher-control.json")).Read(); Assert.True(control.Paused); Assert.Contains("alpha",control.DisabledProfiles); operations.Pause(false); operations.SetProfile("alpha",true); control=new HookLab.Watcher.WatchControlStore(Path.Combine(directory.Path,"watcher-control.json")).Read(); Assert.False(control.Paused); Assert.DoesNotContain("alpha",control.DisabledProfiles); }
	[Fact] public void Audit_view_is_bounded_to_latest_rows() { using var directory=new TemporaryDirectory(); var audit=Path.Combine(directory.Path,"audit.jsonl"); File.WriteAllLines(audit,Enumerable.Range(1,205).Select(value=>value.ToString())); var rows=new CompanionOperations(new(directory.Path,audit)).ReadAudit(); Assert.Equal(200,rows.Count); Assert.Equal("6",rows[0]); Assert.Equal("205",rows[^1]); }
	[Fact] public void Audit_view_can_read_while_the_watcher_holds_the_file_for_writing() { using var directory=new TemporaryDirectory(); var audit=Path.Combine(directory.Path,"audit.jsonl"); using var writer=new FileStream(audit,FileMode.Append,FileAccess.Write,FileShare.Read); using(var text=new StreamWriter(writer,leaveOpen:true)) { text.WriteLine("live"); text.Flush(); } var rows=new CompanionOperations(new(directory.Path,audit)).ReadAudit(); Assert.Equal(new[]{"live"},rows); }
	[Fact] public void Hook_icon_is_a_real_owned_icon() { using var icon=HookIcon.Create(); Assert.Equal(16,icon.Width); Assert.Equal(16,icon.Height); Assert.NotEqual(IntPtr.Zero,icon.Handle); }
	[Fact] public void Task_start_and_restart_use_only_the_installed_task_boundary() { using var directory=new TemporaryDirectory(); var actions=new List<string>(); var operations=new CompanionOperations(new(directory.Path,"audit"),action=>{actions.Add(action);return "ok";}); Assert.Equal("ok",operations.StartTask()); Assert.Equal("ok",operations.RestartTask()); Assert.Equal(new[]{"/Run","/End","/Run"},actions); }
	[Fact] public void Task_privilege_failure_is_not_hidden_or_retried_with_elevation() { using var directory=new TemporaryDirectory(); var operations=new CompanionOperations(new(directory.Path,"audit"),action=>throw new InvalidOperationException("access denied")); var error=Assert.Throws<InvalidOperationException>(()=>operations.StartTask()); Assert.Equal("access denied",error.Message); }
	sealed class TemporaryDirectory:IDisposable { public string Path { get; }=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"hooklab-companion-"+Guid.NewGuid().ToString("N")); public TemporaryDirectory()=>Directory.CreateDirectory(Path); public void Dispose()=>Directory.Delete(Path,true); }
}
