<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.3" />
    <PackageReference Include="xunit" Version="2.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\Extensions\dgSpy.Extension\Identity\ProgramIdentity.cs" Link="Identity\ProgramIdentity.cs" />
    <Compile Include="..\..\Extensions\dgSpy.Extension\Debugger\SessionStateCalculator.cs" Link="Debugger\SessionStateCalculator.cs" />
    <Compile Include="..\..\Extensions\dgSpy.Extension\Events\DebugEventBuffer.cs" Link="Events\DebugEventBuffer.cs" />
    <Compile Include="..\..\Extensions\dgSpy.Extension\Events\OutputBuffer.cs" Link="Events\OutputBuffer.cs" />
    <ProjectReference Include="..\..\dgSpy.Protocol\dgSpy.Protocol.csproj" />
  </ItemGroup>
</Project>
