param([ValidateRange(1024,65535)][int]$Port=18460)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new();$repoRoot=Split-Path $PSScriptRoot -Parent;$runRoot=Join-Path $repoRoot 'artifacts\gateway-control-smoke';$dotnet=(Get-Command dotnet).Source;$gateway=Join-Path $repoRoot 'dgSpy.Gateway\bin\Release\net10.0\dgSpy.Gateway.dll';$process=$null
function Wait-Until([scriptblock]$Condition,[int]$Seconds=20){$deadline=[DateTime]::UtcNow.AddSeconds($Seconds);do{Start-Sleep -Milliseconds 200;if(& $Condition){return $true}}until([DateTime]::UtcNow-ge$deadline);return $false}
try{
	if(Test-Path -LiteralPath $runRoot){Remove-Item -LiteralPath $runRoot -Recurse -Force};New-Item -ItemType Directory -Path $runRoot|Out-Null;[IO.File]::WriteAllText((Join-Path $runRoot 'host.token'),'unused-host-token');[IO.File]::WriteAllText((Join-Path $runRoot 'hosts.json'),'{"hosts":[{"host_id":"host-a","address":"127.0.0.1","port":19999,"token_file":"host.token"}]}')
	$env:DGSPY_URL="http://127.0.0.1:$Port";$env:DGSPY_TOKEN='control-smoke-token';$env:DGSPY_HOSTS_FILE=Join-Path $runRoot 'hosts.json';$env:DGSPY_ACCESS_MODE='inspect-only';$env:DGSPY_AUDIT_FILE=Join-Path $runRoot 'audit.jsonl';Remove-Item Env:DGSPY_REMOTE_ADDRESS -ErrorAction SilentlyContinue
	[Environment]::SetEnvironmentVariable('PATH',$null,[EnvironmentVariableTarget]::Process);$process=Start-Process -FilePath $dotnet -ArgumentList ('"'+$gateway+'"') -WorkingDirectory (Split-Path $gateway) -WindowStyle Hidden -PassThru -RedirectStandardOutput (Join-Path $runRoot 'gateway.out') -RedirectStandardError (Join-Path $runRoot 'gateway.err')
	if(-not(Wait-Until {try{(Invoke-RestMethod "http://127.0.0.1:$Port/health" -TimeoutSec 1).status-eq'ok'}catch{$false}})){throw'Gateway did not become healthy.'}
	$headers=@{'X-dgSpy-Token'='control-smoke-token'};$initialize=@{jsonrpc='2.0';id=1;method='initialize';params=@{protocolVersion='2025-11-25';capabilities=@{};clientInfo=@{name='control-smoke';version='1'}}}|ConvertTo-Json -Depth 8;$initialized=Invoke-WebRequest "http://127.0.0.1:$Port/mcp" -UseBasicParsing -Method Post -ContentType 'application/json' -Headers $headers -Body $initialize;$clientId=$initialized.Headers['Mcp-Session-Id'];if([string]::IsNullOrWhiteSpace($clientId)){throw'initialize did not return Mcp-Session-Id.'};$headers['Mcp-Session-Id']=$clientId;$headers['MCP-Protocol-Version']='2025-11-25'
	$list=@{jsonrpc='2.0';id=2;method='tools/list';params=@{}}|ConvertTo-Json -Depth 5;$tools=((Invoke-RestMethod "http://127.0.0.1:$Port/mcp" -Method Post -ContentType 'application/json' -Headers $headers -Body $list).result.tools).name;if('claim_session'-notin$tools-or'release_session'-notin$tools){throw'Ownership tools are missing.'}
	$call=@{jsonrpc='2.0';id=3;method='tools/call';params=@{name='launch';arguments=@{host_id='host-a';filename='SECRET-NOT-FOR-AUDIT.exe'}}}|ConvertTo-Json -Depth 8;$denied=Invoke-RestMethod "http://127.0.0.1:$Port/mcp" -Method Post -ContentType 'application/json' -Headers $headers -Body $call;if($denied.result.structuredContent.error.code-ne'access_denied'){throw'Inspect-only mode did not deny launch.'};$audit=Get-Content -LiteralPath $env:DGSPY_AUDIT_FILE -Raw;if($audit-notmatch'launch'-or$audit-match'SECRET-NOT-FOR-AUDIT'-or$audit-match'control-smoke-token'){throw'Audit record is missing or not redacted.'}
	Write-Host "PASS: initialize minted a controller, ownership tools were advertised, inspect-only denied mutation, and audit stayed redacted."
}finally{if($process-and-not$process.HasExited){Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue};Remove-Item Env:DGSPY_ACCESS_MODE,Env:DGSPY_AUDIT_FILE -ErrorAction SilentlyContinue}
