using dgSpy.Gateway;
using dgSpy.Protocol;
using System.Text.Json;
using System.Text.Json.Nodes;

var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseUrls(builder.Configuration["DGSPY_URL"] ?? "http://127.0.0.1:7350");
builder.Services.AddSingleton<HostRouter>();
builder.Services.AddSingleton<McpClientSessions>();
builder.Services.AddSingleton<SessionControllers>();
builder.Services.AddSingleton<GatewayAccessPolicy>();
builder.Services.AddSingleton<GatewayAuditLog>();
builder.Services.AddSingleton<GatewayToolExecutor>();
builder.Services.AddHostedService<RemoteHostListener>();
var app = builder.Build();

// Clients authenticate with a local secret. Take it from the environment when set, otherwise mint
// one and write it where a local client can read it — never derive it from anything guessable.
var token = Environment.GetEnvironmentVariable("DGSPY_TOKEN");
var tokenFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "dgSpy", "gateway.token");
if (string.IsNullOrEmpty(token)) {
	token = Convert.ToHexString(System.Security.Cryptography.RandomNumberGenerator.GetBytes(32));
	Directory.CreateDirectory(Path.GetDirectoryName(tokenFile)!);
	File.WriteAllText(tokenFile, token);
	Console.WriteLine($"dgSpy gateway token written to {tokenFile}");
}
Console.WriteLine($"dgSpy gateway listening; send it as the {RequestGuard.TokenHeader} header.");

app.MapGet("/health", () => Results.Json(new { status="ok", protocol_version=ProtocolVersion.Current }));
// dgSpy has no server-initiated MCP messages. Streamable HTTP requires GET to exist, but explicitly
// permits 405 when a server offers no SSE stream.
app.MapGet("/mcp", () => Results.StatusCode(StatusCodes.Status405MethodNotAllowed));
app.MapPost("/mcp", async (HttpContext http, HostRouter rpc, GatewayToolExecutor executor, McpClientSessions clients, CancellationToken cancellationToken) => {
	var rejection = RequestGuard.Reject(http.Request.Headers.Origin, http.Request.Headers[RequestGuard.TokenHeader], token, http.Connection.RemoteIpAddress);
	if (rejection is not null) return Results.Json(new { jsonrpc="2.0", id=(JsonNode?)null, error=new { code=-32600, message=rejection } }, statusCode: StatusCodes.Status403Forbidden);
	using var reader = new StreamReader(http.Request.Body);
	var root = JsonNode.Parse(await reader.ReadToEndAsync(cancellationToken))!.AsObject();
	// JSON-RPC ids are scalar values. Materialize the JsonNode so ASP.NET writes the scalar itself.
	var id = JsonRpcEnvelope.MaterializeId(root["id"]);
	try {
		var method = root["method"]?.GetValue<string>();
		if (method == "initialize") {
			var negotiated=McpProtocol.Negotiate(root["params"]?["protocolVersion"]?.GetValue<string>());
			var clientId=clients.Create(); http.Response.Headers[McpClientSessions.Header]=clientId;
			return Results.Json(new { jsonrpc="2.0", id, result=new { protocolVersion=negotiated, capabilities=new { tools=new { listChanged=false } }, serverInfo=new { name="dgSpy", version="0.1.0" } } });
		}
		if (!McpProtocol.IsValidRequestVersion(http.Request.Headers[McpProtocol.VersionHeader]))
			return Results.BadRequest(new { jsonrpc="2.0", id, error=new { code=-32600, message=$"Unsupported {McpProtocol.VersionHeader}. Supported: {string.Join(", ",McpProtocol.Supported)}." } });
		// Accepted JSON-RPC notifications have no response body and use 202 in Streamable HTTP.
		if (id is null) return Results.Accepted();
		var client=clients.Resolve(http.Request.Headers[McpClientSessions.Header]);
		if (method == "tools/list") return Results.Json(new { jsonrpc="2.0", id, result=new { tools=ToolCatalog.All } });
		if (method != "tools/call") return McpError(id, -32601, "Method not found");
		var name=root["params"]?["name"]?.GetValue<string>() ?? ""; var args=root["params"]?["arguments"] as JsonObject ?? new JsonObject();
		if (name=="list_hosts") {
			var hosts=await rpc.ListHostsAsync(cancellationToken);
			return Results.Json(new { jsonrpc="2.0",id,result=new { structuredContent=new { hosts },content=new[] { new { type="text",text=ProtocolJson.Serialize(hosts) } } } });
		}
		var response=await executor.ExecuteAsync(name,args,client,cancellationToken);
		if (response.Error is not null) return Results.Json(new { jsonrpc="2.0", id, result=new { isError=true, structuredContent=new { error=response.Error }, content=new[] { new { type="text", text=response.Error.Message } } } });
		var structured=response.Result is null ? null : ProtocolJson.ToNode(response.Result);
		return Results.Json(new { jsonrpc="2.0", id, result=new { structuredContent=structured, content=new[] { new { type="text", text=ProtocolJson.Serialize(response.Result) } } } });
	} catch (Exception ex) { return McpError(id, -32603, ex.Message); }
});
try { app.Run(); }
catch (Exception ex) {
	var fatalLog=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"dgSpy","gateway-fatal.log");
	var detail=$"[{DateTime.UtcNow:O}] {ex}\n"; var saved=false;
	try { Directory.CreateDirectory(Path.GetDirectoryName(fatalLog)!); File.AppendAllText(fatalLog,detail); saved=true; } catch { }
	Console.Error.WriteLine(saved ? $"dgSpy Gateway stopped: {ex.Message}. Details: {fatalLog}" : $"dgSpy Gateway stopped: {ex}");
	Environment.ExitCode=1;
}
static IResult McpError(object? id, int code, string message) => Results.Json(new { jsonrpc="2.0", id, error=new { code, message } });

public static class ToolCatalog {
	static object Tool(string name,string description,object properties,string[]? required=null,bool routed=true) {
		var routedProperties=new Dictionary<string,object>();
		if (routed) routedProperties["host_id"]=new { type="string",description="Registered debugger host. Optional only when exactly one host is configured." };
		foreach (var property in properties.GetType().GetProperties()) routedProperties[property.Name]=property.GetValue(properties)!;
		var requiredProperties=(required ?? Array.Empty<string>()).ToList();
		if (CapabilityCatalog.Operations.Any(item=>item.Operation==name && item.MutatesSession) && routedProperties.ContainsKey("session_id")) {
			if(!routedProperties.ContainsKey("expected_state_version")) routedProperties["expected_state_version"]=new { type="integer",description="Required exact state_version for every session mutation." };
			if(!requiredProperties.Contains("expected_state_version")) requiredProperties.Add("expected_state_version");
		}
		return new { name,description,inputSchema=new { type="object",properties=routedProperties,required=requiredProperties.ToArray() } };
	}
	static object EvalMutationSchema() => new { session_id=new { type="string" },expression=new { type="string",description="Complete call or new-expression." },thread_id=new { type="string" },frame_index=new { type="integer",minimum=0 },timeout_ms=new { type="integer",minimum=1,maximum=10000,description="Hard engine func-eval timeout; default 1000." } };
	/// <summary>Margin between the extension's own bound for an operation and the gateway's deadline for
	/// it. The gateway deadline must outlast the inner bound, or the gateway abandons work that was about
	/// to succeed — a flat 8 s once cut off a successful 10 s attach.</summary>
	public const int MarginSeconds = 5;
	/// <summary>Derived from the extension's advertised bound rather than guessed. CapabilityCatalog is
	/// the single source of truth for both sides; get_capabilities serves the same table to callers.</summary>
	public static int DeadlineSeconds(string tool) {
		var bound=CapabilityCatalog.BoundMs(tool);
		return bound<=0 ? 8 : (int)Math.Ceiling(bound/1000.0)+MarginSeconds;
	}
	public static readonly object[] All = {
		Tool("list_hosts", "List registered debugger hosts and their current connection state.", new {},routed:false),
		Tool("get_host_info", "Identify the dnSpy host this gateway talks to: versions, machine, architecture, supported engines, and whether a session is live.", new {}),
		Tool("get_capabilities", "Report what this host supports before relying on it: per-operation time bounds, per-engine behavior (notably that Mono/Unity binds breakpoints only at sequence points), limits, and the complete event_kinds and stop_reasons vocabularies. Engine differences are advertised here rather than assumed.", new {}),
		Tool("list_programs", "List dnSpy-attachable managed runtimes. Unfiltered enumeration probes every process on the machine and takes seconds; pass process_ids or process_names when the target is known. Each call replaces the set of valid program_id values.", new { process_ids=new { type="array", items=new { type="integer" }, description="Only these PIDs." }, process_names=new { type="array", items=new { type="string" }, description="Process names, wildcards * and ? allowed, eg. UltimateChickenHorse*." }, provider_names=new { type="array", items=new { type="string" }, description="dnSpy attach providers to consult: DotNetFramework, DotNet, UnityEditor, UnityPlayer. Naming providers skips the rest. UnityPlayer runs a multicast scan and is skipped entirely unless named." } }),
		Tool("attach", "Attach using a program_id returned by list_programs.", new { program_id=new { type="string" } }, new[]{"program_id"}),
		Tool("attach_endpoint", "Attach to a Mono/Unity soft-debugger endpoint by address and port. Use this when the target was launched with --debugger-agent=transport=dt_socket,server=y,address=HOST:PORT: such a target emits no discovery beacon, so list_programs can never see it and attach cannot reach it. Returns state \"faulted\" with fault_message when the connection fails.", new { address=new { type="string", description="Default 127.0.0.1." }, port=new { type="integer", minimum=1, maximum=65535 }, engine=new { type="string", @enum=new[]{"unity","mono"}, description="Default unity. Must match the target's runtime." }, process_is_suspended=new { type="boolean", description="True when the agent was given suspend=y, ie. the target is parked waiting for a debugger." }, connection_timeout_ms=new { type="integer", description="Socket retry window. dnSpy's default is 10000; capped at 300000." } }, new[]{"port"}),
		Tool("launch", "Launch a target through dnSpy's debugger engine. Unlike attach, dnSpy owns the process, so terminate and restart have deterministic semantics.", new { filename=new { type="string" }, engine=new { type="string", @enum=new[]{"cordebug","unity"}, description="Default cordebug." }, command_line=new { type="string" }, working_directory=new { type="string" }, break_at=new { type="string", @enum=new[]{"none","create_process","entry_point"} }, environment=new { type="object", additionalProperties=new { type="string" } }, connection_timeout_ms=new { type="integer", minimum=1, maximum=300000 } }, new[]{"filename"}),
		Tool("get_session_state", "Get current debugger session state.", new { session_id=new { type="string" } }, new[]{"session_id"}),
		Tool("list_sessions", "List active debugger sessions. Use this to recover a session_id.", new {}),
		Tool("get_session_controller", "Report whether a debugger session currently has an MCP controller. Inspection never claims it or changes target state.", new { session_id=new { type="string" } },new[]{"session_id"}),
		Tool("claim_session", "Explicitly claim an unowned or expired debugger session after caller or Gateway recovery. Never changes target state.", new { session_id=new { type="string" } },new[]{"session_id"}),
		Tool("release_session", "Release controller ownership without resuming, detaching, terminating, or otherwise changing the target.", new { session_id=new { type="string" } },new[]{"session_id"}),
		Tool("detach", "Detach one selected process or all targets. Fails with detach_would_terminate unless allow_terminate is explicit. If the engine does not actually remove the target within 10 seconds, returns detach_timed_out and preserves the session instead of claiming success.", new { session_id=new { type="string" },process_id=new { type="integer" }, allow_terminate=new { type="boolean", description="Stop debugging even if that terminates the selected target." } }, new[]{"session_id"}),
		Tool("terminate", "Terminate one selected process or every active target explicitly.", new { session_id=new { type="string" },process_id=new { type="integer" } }, new[]{"session_id"}),
		Tool("restart", "Restart a target previously launched through dgSpy. Attached targets cannot be restarted because dgSpy does not own their launch options.", new { session_id=new { type="string" } }, new[]{"session_id"}),
		Tool("pause", "Pause one process. process_id is optional only when exactly one process is active.", new { session_id=new { type="string" }, process_id=new { type="integer" }, expected_state_version=new { type="integer" } }, new[]{"session_id"}),
		Tool("continue", "Continue one process. process_id is optional only when exactly one process is active.", new { session_id=new { type="string" }, process_id=new { type="integer" }, expected_state_version=new { type="integer" } }, new[]{"session_id"}),
		Tool("set_il_breakpoint", "Set an exact module/token/IL-offset breakpoint and report whether the engine actually bound it. Check `bound`: false with severity \"error\" will never be hit, false with no error is pending a module load. On Mono/Unity a breakpoint can only sit on a sequence point; many offsets qualify but a frame's own il_offset often does not, and a refused one is retried at method entry (offset 0) unless snap_to_sequence_point is false — when that happens `snapped` is true and it stops earlier than requested. Pass the returned `cursor_event_id` to wait_for_stop as after_event_id: a cursor read after this call has already missed the first hit on a hot method.", new { session_id=new { type="string" }, module=new { type="string" }, method_token=new { type="integer" }, il_offset=new { type="integer" }, snap_to_sequence_point=new { type="boolean", description="Default true. Retry at method entry when the engine refuses the requested offset." } }, new[]{"session_id","module","method_token","il_offset"}),
		Tool("list_breakpoints", "List all dnSpy breakpoints with their binding state. Breakpoints are global and outlive a session.", new {}),
		Tool("remove_breakpoint", "Remove one breakpoint by the exact id returned by set_il_breakpoint or list_breakpoints. Unlike clear_breakpoints, this leaves every other dnSpy and UI breakpoint untouched.", new { breakpoint_id=new { type="integer" } }, new[]{"breakpoint_id"}),
		Tool("clear_breakpoints", "Remove every dnSpy breakpoint, including any set by hand in the dnSpy UI. Breakpoints outlive a detach and rebind on the next attach, so clear them before reattaching if a fresh session should not stop on old ones.", new {}),
		Tool("wait_for_stop", "Wait without polling for the next normalized stop after an event cursor. Concurrent waiters do not consume events. A truncated result supplies oldest_available_cursor so the caller can recover.", new { session_id=new { type="string" }, after_event_id=new { type="integer" }, timeout_ms=new { type="integer", minimum=1, maximum=10000, description="Default 5000. The extension clamps to 10000; poll again with the returned cursor for longer waits." } }, new[]{"session_id"}),
		Tool("wait_for_event", "Wait without polling for any requested event kinds after a cursor. Returns immediately when a matching buffered event already exists; concurrent waiters are non-destructive.", new { session_id=new { type="string" }, after_event_id=new { type="integer" }, kinds=new { type="array", items=new { type="string", @enum=EventKinds.All }, description="Optional normalized event-kind filter. An unrecognized kind is rejected with invalid_argument rather than silently matching nothing." }, timeout_ms=new { type="integer", minimum=1, maximum=10000, description="Default 5000. The extension clamps to 10000." } }, new[]{"session_id"}),
		Tool("get_events", "Read normalized lifecycle and debugger events without consuming them. Optional kinds filter the bounded per-session stream; truncated reports when the requested cursor is older than retained history.", new { session_id=new { type="string" }, after_event_id=new { type="integer" }, kinds=new { type="array", items=new { type="string", @enum=EventKinds.All }, description="Optional normalized event-kind filter. An unrecognized kind is rejected with invalid_argument rather than silently matching nothing." } }, new[]{"session_id"}),
		Tool("get_stop_reason", "Read the latest normalized stop, or an exact retained stop event by event_id, including process, thread, breakpoint, exception, and location details when supplied by the debugger. stop_reason is one of: breakpoint, exception, step, entry_point, program_break, pause, unknown.", new { session_id=new { type="string" }, event_id=new { type="integer" } }, new[]{"session_id"}),
		Tool("list_threads", "List paused target threads with stable thread_id values. It does not eagerly fetch every stack because Unity threads can exit during frame retrieval; select a returned thread_id with get_callstack or get_frame.", new { session_id=new { type="string" } }, new[]{"session_id"}),
		Tool("get_callstack", "Get a paused call stack and primitive locals. Pass thread_id for deterministic caller-selected inspection; omitting it preserves the managed-frame probe fallback.", new { session_id=new { type="string" }, thread_id=new { type="string" }, max_frames=new { type="integer", minimum=1, maximum=100 } }, new[]{"session_id"}),
		Tool("get_frame", "Inspect one paused frame by caller-selected thread_id and zero-based frame_index. `locals` holds primitive scalars only; pass include to also get objects and `this` in `values`, which is one round trip against one evaluation context.", new { session_id=new { type="string" }, thread_id=new { type="string" }, frame_index=new { type="integer", minimum=0, maximum=99 }, include=new { type="array", items=new { type="string", @enum=new[]{"locals","this"} }, description="locals covers arguments too — dnSpy does not separate them. Unknown values are rejected rather than ignored." }, allow_func_eval=new { type="boolean", description="Default false." } }, new[]{"session_id","thread_id","frame_index"}),
		Tool("update_breakpoint", "Change an existing breakpoint's enabled state, condition, hit count, or trace message. Conditions and hit counts are evaluated by the engine inside the target, so a condition that cannot be evaluated fails at hit time rather than here. Pass an empty string for condition or trace_message to clear it; omit a field to leave it unchanged.", new { breakpoint_id=new { type="integer" }, enabled=new { type="boolean" }, condition=new { type="string", description="Expression in the target's language. Empty string clears the condition." }, condition_kind=new { type="string", @enum=BreakpointConditionKinds.All, description="Default is_true. when_changed stops when the value differs from the previous hit." }, hit_count=new { type="integer", minimum=1 }, hit_count_kind=new { type="string", @enum=HitCountKinds.All, description="Default equals (stop on exactly the nth hit)." }, trace_message=new { type="string", description="Print instead of (or as well as) stopping. Empty string clears." }, trace_continue=new { type="boolean", description="Default true: print and keep running, which produces NO stopped event. Pass false to print and stop." } }, new[]{"breakpoint_id"}),
		Tool("set_exception_breakpoint", "Stop when an exception is thrown. Pass a fully qualified type name, or omit name to set the category's default that governs every exception it does not name. Like code breakpoints these are dnSpy-global and outlive a session.", new { category=new { type="string", description="Default DotNet." }, name=new { type="string", description="Fully qualified type, eg. System.InvalidOperationException. Omit for the category default." }, stop_first_chance=new { type="boolean", description="Stop when thrown, before the target gets to handle it." }, stop_second_chance=new { type="boolean", description="Stop when it goes unhandled." } }),
		Tool("list_exception_breakpoints", "List exceptions configured to break on throw. By default this reports first-chance entries only, which is the set someone deliberately configured: dnSpy stops on SECOND chance for essentially every .NET exception it knows, so including those returns thousands of identical stock entries that say nothing about this session. Bounded, with total and truncated.", new { include_second_chance=new { type="boolean", description="Default false. True adds dnSpy's stock second-chance defaults — expect thousands of entries." }, max_results=new { type="integer", minimum=1, maximum=1000, description="Default 200." } }),
		Tool("step_into", "Step into the call at the current instruction. The stop arrives on the event stream like any other, with stop_reason \"step\": pass the returned cursor_event_id to wait_for_stop. completed=false means the step is still running, not that it failed.", new { session_id=new { type="string" }, thread_id=new { type="string", description="Defaults to the thread that carried the stop. Stepping the wrong thread resumes the target and stops somewhere unrelated, so pass this explicitly when several threads are interesting." }, expected_state_version=new { type="integer" } }, new[]{"session_id"}),
		Tool("step_over", "Step over the call at the current instruction. See step_into for how completion is reported.", new { session_id=new { type="string" }, thread_id=new { type="string" }, expected_state_version=new { type="integer" } }, new[]{"session_id"}),
		Tool("step_out", "Run to the caller of the current frame. See step_into for how completion is reported.", new { session_id=new { type="string" }, thread_id=new { type="string" }, expected_state_version=new { type="integer" } }, new[]{"session_id"}),
		Tool("evaluate", "Evaluate an expression against a paused frame. Returns the raw scalar and dnSpy's formatted display text as separate fields, so numbers stay comparable without parsing display text. has_raw_value distinguishes a value of null from a value that is unavailable or optimized away. Func-eval is OFF by default: an expression that calls a property getter runs code inside the target, which can deadlock a target holding a lock and can mutate what you were inspecting.", new { session_id=new { type="string" }, expression=new { type="string" }, thread_id=new { type="string", description="Defaults to the thread that carried the stop." }, frame_index=new { type="integer", minimum=0, description="Default 0." }, allow_func_eval=new { type="boolean", description="Default false. True permits running target code, eg. property getters and ToString." }, allow_side_effects=new { type="boolean", description="Default false." } }, new[]{"session_id","expression"}),
		Tool("invoke_method", "SIDE EFFECTING and audited. Evaluate a complete method-call expression in the paused target. Func-eval and side effects are always enabled by this tool boundary and cannot be downgraded or enabled accidentally through evaluate.", EvalMutationSchema(), new[]{"session_id","expression"}),
		Tool("create_object", "SIDE EFFECTING and audited. Evaluate a complete object-construction expression in the paused target. Func-eval and side effects are always enabled.", EvalMutationSchema(), new[]{"session_id","expression"}),
		Tool("read_memory", "Read up to 65536 bytes from the selected debug process. Returns base64 and the runtime capability used.", new { session_id=new { type="string" }, process_id=new { type="integer" }, address=new { type="integer", minimum=0 }, length=new { type="integer", minimum=1, maximum=65536 } }, new[]{"session_id","address","length"}),
		Tool("write_memory", "SIDE EFFECTING and audited. Write up to 65536 base64-encoded bytes to the selected debug process.", new { session_id=new { type="string" }, process_id=new { type="integer" }, address=new { type="integer", minimum=0 }, data_base64=new { type="string" } }, new[]{"session_id","address","data_base64"}),
		Tool("get_disassembly", "Return managed IL or the selected frame's JIT native code blocks. Unsupported native bodies return a structured capability failure.", new { session_id=new { type="string" }, mode=new { type="string", @enum=new[]{"managed","native"} }, module=new { type="string", description="Required with managed mode." }, method_token=new { type="integer", description="Required with managed mode." }, thread_id=new { type="string" }, frame_index=new { type="integer", minimum=0 } }, new[]{"session_id"}),
		Tool("get_registers", "Return registers when exposed by the active runtime. This dnSpy contract does not expose them, so callers receive capability_unsupported instead of an empty successful result.", new { session_id=new { type="string" }, thread_id=new { type="string" } }, new[]{"session_id"}),
		Tool("set_instruction_pointer", "SIDE EFFECTING and audited. Move the selected thread within its current managed method after engine CanSetIP validation.", new { session_id=new { type="string" }, thread_id=new { type="string" }, frame_index=new { type="integer", minimum=0 }, module=new { type="string" }, method_token=new { type="integer" }, il_offset=new { type="integer", minimum=0 } }, new[]{"session_id","module","method_token","il_offset"}),
		Tool("get_members", "Expand one object one level, paged. Pass a returned member's `expression` back here to go deeper: depth is deliberately the caller's to control, because recursing server-side is unbounded on a cyclic object graph. Reports total and truncated.", new { session_id=new { type="string" }, expression=new { type="string" }, thread_id=new { type="string" }, frame_index=new { type="integer", minimum=0 }, offset=new { type="integer", minimum=0, description="Default 0." }, count=new { type="integer", minimum=1, maximum=200, description="Default 50." }, allow_func_eval=new { type="boolean", description="Default false." } }, new[]{"session_id","expression"}),
		Tool("set_value", "Assign to a local, parameter, field or property in the paused target. Always side-effecting: the assignment executes in the target. compiler_error=true means the expression did not compile and nothing ran; an error without it means the target may already have been touched.", new { session_id=new { type="string" }, expression=new { type="string", description="What to assign to, eg. input or this.counter." }, value=new { type="string", description="Expression producing the new value, eg. 42." }, thread_id=new { type="string" }, frame_index=new { type="integer", minimum=0 }, allow_func_eval=new { type="boolean", description="Default false." } }, new[]{"session_id","expression","value"}),
		Tool("get_exception", "Get the exception that stopped the target, from dnSpy's own exceptions provider rather than a typed expression. An empty array is a normal answer: most stops are not exception stops.", new { session_id=new { type="string" }, thread_id=new { type="string" }, frame_index=new { type="integer", minimum=0 }, allow_func_eval=new { type="boolean" } }, new[]{"session_id"}),
		Tool("add_watch", "Store an expression to re-evaluate later. Watches are expressions, not value handles: a handle goes stale on the next resume, an expression survives it. Adding the same expression twice returns the existing watch_id.", new { session_id=new { type="string" }, expression=new { type="string" } }, new[]{"session_id","expression"}),
		Tool("list_watches", "Evaluate every stored watch against a paused frame in one pass. A watch whose expression fails reports its own error instead of failing the call, so one bad expression cannot hide the rest.", new { session_id=new { type="string" }, thread_id=new { type="string" }, frame_index=new { type="integer", minimum=0 }, allow_func_eval=new { type="boolean" } }, new[]{"session_id"}),
		Tool("remove_watch", "Remove one stored watch by id.", new { session_id=new { type="string" }, watch_id=new { type="integer" } }, new[]{"session_id","watch_id"}),
		Tool("list_modules", "List loaded modules for every runtime in the session. can_set_breakpoint reflects whether the engine publishes a stable ModuleId; metadata-backed in-memory and dynamic modules are supported even without a file path.", new { session_id=new { type="string" } }, new[]{"session_id"}),
		Tool("list_documents", "List loaded modules with their metadata state: assembly full name, type count, and whether dnSpy could load metadata at all. A module whose metadata fails to load is reported with has_metadata=false rather than omitted, because a silently missing module makes a type that exists look like it does not.", new { session_id=new { type="string" } }, new[]{"session_id"}),
		Tool("list_types", "List types in a loaded module, filtered and paged. Each result carries the metadata token, so a breakpoint can be set from it without parsing display text.", new { session_id=new { type="string" }, module=new { type="string", description="Full path, filename, or module name from list_modules." }, name_pattern=new { type="string", description="Case-insensitive substring match on the full type name." }, offset=new { type="integer", minimum=0 }, count=new { type="integer", minimum=1, maximum=500, description="Default 100." } }, new[]{"session_id","module"}),
		Tool("list_members", "List methods, fields, properties and events of a type, with metadata tokens. An ambiguous type name is reported with the candidates rather than resolved by guessing.", new { session_id=new { type="string" }, module=new { type="string" }, type=new { type="string", description="Full type name, or a unique short name." }, name_pattern=new { type="string" }, offset=new { type="integer", minimum=0 }, count=new { type="integer", minimum=1, maximum=500, description="Default 200." } }, new[]{"session_id","module","type"}),
		Tool("search_symbols", "Find types and members by name across loaded modules. This is how you get from a name to the module and metadata token a breakpoint needs, without knowing a token up front. Bounded; reports total and truncated. Pass module to avoid searching every loaded assembly, which on Unity means thousands of framework types.", new { session_id=new { type="string" }, pattern=new { type="string", description="Case-insensitive substring." }, kinds=new { type="array", items=new { type="string", @enum=new[]{"type","method","field"} }, description="Default [type, method]." }, module=new { type="string", description="Substring filter on module name or path." }, count=new { type="integer", minimum=1, maximum=500, description="Default 100." } }, new[]{"session_id","pattern"}),
		Tool("get_il", "Disassemble a method to IL with offsets and operands. is_sequence_point marks the offsets Mono will accept a breakpoint at — it rejects every other one with NO_SEQ_POINT_AT_IL_OFFSET, which dnSpy turns into a silently unbound breakpoint. has_sequence_points=false means no PDB was available, NOT that there are no legal offsets. Identify the method by method_token, or by type plus method.", new { session_id=new { type="string" }, module=new { type="string" }, method_token=new { type="integer" }, type=new { type="string" }, method=new { type="string" }, signature=new { type="string", description="Full name of the intended overload, when type+method is ambiguous." } }, new[]{"session_id","module"}),
        Tool("get_csharp", "Decompile a method, or a whole type with whole_type=true. Identify a method by method_token or by type plus method.", new { session_id=new { type="string" }, module=new { type="string" }, method_token=new { type="integer" }, type=new { type="string" }, method=new { type="string" }, signature=new { type="string" }, whole_type=new { type="boolean", description="Default false. True decompiles the entire type, which can be very large." } }, new[]{"session_id","module"}),
		Tool("set_breakpoint", "Set a breakpoint by type and method name instead of a metadata token. Resolves the name, then takes exactly the same path as set_il_breakpoint, so binding state, Mono sequence-point snapping and cursor_event_id behave identically — read that tool's description. Overloads are reported as ambiguous with their full names rather than resolved by guessing.", new { session_id=new { type="string" }, module=new { type="string" }, type=new { type="string" }, method=new { type="string" }, signature=new { type="string", description="Full name of the intended overload." }, il_offset=new { type="integer", description="Default 0 (method entry)." }, snap_to_sequence_point=new { type="boolean", description="Default true." } }, new[]{"session_id","module","type","method"}),
		Tool("search_text", "Search decompiled C# text in loaded modules. Output and work are bounded; scan_truncated means max_methods stopped the scan before the selected scope was exhausted. Pass module and type on Unity.", new { session_id=new { type="string" }, pattern=new { type="string" }, module=new { type="string" }, type=new { type="string", description="Optional declaring-type substring." }, count=new { type="integer", minimum=1, maximum=200 }, max_methods=new { type="integer", minimum=1, maximum=1000, description="Hard work bound; default 200." } }, new[]{"session_id","pattern"}),
		Tool("find_references", "Find loaded methods whose IL references a target metadata member. The target is module plus token; search_module optionally limits the scan.", new { session_id=new { type="string" }, module=new { type="string" }, token=new { type="integer" }, search_module=new { type="string" }, count=new { type="integer", minimum=1, maximum=500 } }, new[]{"session_id","module","token"}),
		Tool("find_implementations", "Find directly derived types and direct interface implementers. search_module limits the loaded modules scanned and should be used on Unity.", new { session_id=new { type="string" }, module=new { type="string" }, token=new { type="integer" }, type=new { type="string" }, search_module=new { type="string" }, count=new { type="integer", minimum=1, maximum=500 } }, new[]{"session_id","module"}),
		Tool("get_metadata", "Return bounded metadata facts for a module and optionally resolve one metadata token.", new { session_id=new { type="string" }, module=new { type="string" }, token=new { type="integer" } }, new[]{"session_id","module"}),
		Tool("create_object_id", "Create a runtime-scoped persistent object ID for an evaluated C# expression.", new { session_id=new { type="string" },expression=new { type="string" },process_id=new { type="integer" },runtime_id=new { type="string" },thread_id=new { type="string" },frame_index=new { type="integer",minimum=0 },allow_func_eval=new { type="boolean" } },new[]{"session_id","expression"}),
		Tool("list_object_ids", "List object IDs in one explicitly selected runtime.", new { session_id=new { type="string" },process_id=new { type="integer" },runtime_id=new { type="string" } },new[]{"session_id"}),
		Tool("evaluate_object_id", "Evaluate a persistent object ID in a paused frame.", new { session_id=new { type="string" },object_id=new { type="integer",minimum=0 },process_id=new { type="integer" },runtime_id=new { type="string" },thread_id=new { type="string" },frame_index=new { type="integer",minimum=0 },allow_func_eval=new { type="boolean" } },new[]{"session_id","object_id"}),
		Tool("release_object_id", "Release one runtime-scoped object ID.", new { session_id=new { type="string" },object_id=new { type="integer",minimum=0 },process_id=new { type="integer" },runtime_id=new { type="string" } },new[]{"session_id","object_id"}),
		Tool("get_autos", "Return the C# Autos provider values for a selected paused frame, capped at 200.", new { session_id=new { type="string" },process_id=new { type="integer" },runtime_id=new { type="string" },thread_id=new { type="string" },frame_index=new { type="integer",minimum=0 },allow_func_eval=new { type="boolean" } },new[]{"session_id"}),
		Tool("get_output", "Read the bounded non-destructive debugger output stream after a cursor.", new { session_id=new { type="string" },after_output_id=new { type="integer",minimum=0 } },new[]{"session_id"}),
		Tool("wait_for_output", "Wait for debugger output after a cursor without consuming it.", new { session_id=new { type="string" },after_output_id=new { type="integer",minimum=0 },timeout_ms=new { type="integer",minimum=1,maximum=10000 } },new[]{"session_id"}),
		Tool("set_module_breakpoint", "Stop on module load or unload using dnSpy module filters.", ModuleBreakpointSchema(),new[]{"session_id"}),
		Tool("list_module_breakpoints", "List global dnSpy module breakpoints.", new { session_id=new { type="string" } },new[]{"session_id"}),
		Tool("update_module_breakpoint", "Update one module breakpoint; omitted filters remain unchanged.", ModuleBreakpointSchema(true),new[]{"session_id","breakpoint_id"}),
		Tool("remove_module_breakpoint", "Remove one module breakpoint.", new { session_id=new { type="string" },breakpoint_id=new { type="integer" } },new[]{"session_id","breakpoint_id"}),
		Tool("export_breakpoints", "Export code, trace, module, and exception policies as bounded canonical dgspy.breakpoints v1 JSON.", new { session_id=new { type="string" },max_exception_policies=new { type="integer",minimum=1,maximum=5000 } },new[]{"session_id"}),
		Tool("import_breakpoints", "Validate, dry-run, merge, or explicitly replace breakpoints from canonical JSON.", new { session_id=new { type="string" },document=new { type="object" },mode=new { type="string",@enum=new[]{"merge","replace"} },dry_run=new { type="boolean" } },new[]{"session_id","document"}),
		Tool("list_exception_categories", "List dnSpy exception categories.", new { session_id=new { type="string" } },new[]{"session_id"}),
		Tool("list_exception_policies", "List bounded exception definitions with flags and module conditions.", new { session_id=new { type="string" },count=new { type="integer",minimum=1,maximum=2000 } },new[]{"session_id"}),
		Tool("set_exception_policy", "Add or replace thrown/unhandled flags and module conditions for an exception.", ExceptionPolicySchema(),new[]{"session_id"}),
		Tool("remove_exception_policy", "Remove one exception policy.", new { session_id=new { type="string" },category=new { type="string" },name=new { type="string" } },new[]{"session_id"}),
		Tool("restore_exception_defaults", "Reset dnSpy exception policies to defaults and remove user additions.", new { session_id=new { type="string" } },new[]{"session_id"}),
		Tool("get_value_export", "Serialize a supported evaluated value as bounded base64 chunks with whole-value SHA-256.", ValueExportSchema(),new[]{"session_id","expression"}),
		Tool("write_value_export", "SIDE EFFECTING and audited. Write an evaluated value below DGSPY_EXPORT_ROOT; no overwrite by default.", new { session_id=new { type="string" },expression=new { type="string" },path=new { type="string" },overwrite=new { type="boolean" },process_id=new { type="integer" },runtime_id=new { type="string" },thread_id=new { type="string" },frame_index=new { type="integer",minimum=0 } },new[]{"session_id","expression","path"}),
		Tool("analyze_symbol", "Return bounded typed caller, callee, construction, field, override, implementation, and attribute edges.", new { session_id=new { type="string" },module=new { type="string" },token=new { type="integer" },search_module=new { type="string" },count=new { type="integer",minimum=1,maximum=500 },max_methods=new { type="integer",minimum=1,maximum=5000 } },new[]{"session_id","module","token"}),
		Tool("get_raw_module", "Read a loaded module image as a paged base64 chunk with total size and SHA-256. File-less modules are reconstructed from runtime metadata.", new { session_id=new { type="string" }, module=new { type="string" }, offset=new { type="integer", minimum=0 }, count=new { type="integer", minimum=1, maximum=1048576 } }, new[]{"session_id","module"})
	};
	static object ModuleBreakpointSchema(bool includeId=false)=>new { session_id=new { type="string" },breakpoint_id=new { type="integer" },enabled=new { type="boolean" },module_name=new { type="string" },is_dynamic=new { type="boolean" },is_in_memory=new { type="boolean" },is_loaded=new { type="boolean" },order=new { type="integer",minimum=0 },process_name=new { type="string" },app_domain_name=new { type="string" } };
	static object ExceptionPolicySchema()=>new { session_id=new { type="string" },category=new { type="string" },name=new { type="string" },stop_thrown=new { type="boolean" },stop_unhandled=new { type="boolean" },conditions=new { type="array",items=new { type="object" } } };
	static object ValueExportSchema()=>new { session_id=new { type="string" },expression=new { type="string" },process_id=new { type="integer" },runtime_id=new { type="string" },thread_id=new { type="string" },frame_index=new { type="integer",minimum=0 },offset=new { type="integer",minimum=0 },count=new { type="integer",minimum=1,maximum=1048576 } };
}
