<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <UseWindowsForms>true</UseWindowsForms>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>
</Project>
