using System;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using dgSpy.Protocol;
using dnSpy.Contracts.Debugger;
using dnSpy.Contracts.Debugger.Breakpoints.Modules;
using dnSpy.Contracts.Debugger.Evaluation;
using dnSpy.Contracts.Debugger.Exceptions;

namespace dgSpy.Extension {
	sealed partial class RpcHost {
		DbgRuntime SelectRuntime(RpcRequest req) {
			var process=SelectProcess(req); var requested=(string?)req.Arguments["runtime_id"]; var runtimes=process.Runtimes.ToArray();
			if(string.IsNullOrEmpty(requested) && runtimes.Length==1) return runtimes[0];
			var matches=runtimes.Where(r=>StringComparer.OrdinalIgnoreCase.Equals(r.Guid.ToString("D"),requested) || StringComparer.OrdinalIgnoreCase.Equals(r.Name,requested)).ToArray();
			if(matches.Length==1) return matches[0];
			throw new RpcException(requested is null ? "ambiguous_target" : "runtime_not_found",requested is null ? "More than one runtime is active; pass runtime_id." : $"Runtime {requested} is not active in process {process.Id}.");
		}

		async Task<ObjectIdInfo> CreateObjectIdAsync(RpcRequest req,CancellationToken cancellationToken) {
			CheckSession(req); var expression=(string?)req.Arguments["expression"]; if(string.IsNullOrWhiteSpace(expression)) throw new RpcException("invalid_arguments","expression is required.");
			return await WithEvaluationAsync(req,(captured,eval)=>{
				ValidateRuntime(req,captured.Frame.Runtime); var nodes=CreateNodes(captured,eval,new[]{expression!},allowFuncEval:(bool?)req.Arguments["allow_func_eval"]??false,allowSideEffects:false);
				try { var value=nodes[0].Value ?? throw new RpcException("value_unavailable",nodes[0].ErrorMessage ?? "The expression has no value."); if(!objectIds.CanCreateObjectId(value)) throw new RpcException("capability_unsupported","This runtime cannot create an object ID for the evaluated value."); var id=objectIds.CreateObjectId(value) ?? throw new RpcException("capability_unavailable","The runtime refused to create the object ID."); return DescribeObjectId(id,expression!,DescribeNode(nodes[0],eval,expression!)); }
				finally { manager.Close(nodes); }
			},cancellationToken).ConfigureAwait(false);
		}
		async Task<ObjectIdInfo[]> ListObjectIdsAsync(RpcRequest req,CancellationToken cancellationToken) { CheckSession(req); return await OnDebuggerAsync(()=>{ var runtime=SelectRuntime(req); return objectIds.GetObjectIds(runtime).Select(id=>DescribeObjectId(id,"$"+id.Id,null)).ToArray(); },cancellationToken).ConfigureAwait(false); }
		async Task<ObjectIdInfo> EvaluateObjectIdAsync(RpcRequest req,CancellationToken cancellationToken) { CheckSession(req); var number=(uint?)req.Arguments["object_id"] ?? throw new RpcException("invalid_arguments","object_id is required."); return await WithEvaluationAsync(req,(captured,eval)=>{ ValidateRuntime(req,captured.Frame.Runtime); var id=objectIds.GetObjectId(captured.Frame.Runtime,number) ?? throw new RpcException("object_id_not_found",$"Object ID ${number} is not active in the selected runtime."); var nodes=captured.Language.ValueNodeFactory.Create(eval,new[]{id},NodeOptions((bool?)req.Arguments["allow_func_eval"]??false)); try { return DescribeObjectId(id,"$"+number,DescribeNode(nodes[0],eval,"$"+number)); } finally { manager.Close(nodes); } },cancellationToken).ConfigureAwait(false); }
		async Task<ObjectIdInfo> ReleaseObjectIdAsync(RpcRequest req,CancellationToken cancellationToken) { CheckSession(req); var number=(uint?)req.Arguments["object_id"] ?? throw new RpcException("invalid_arguments","object_id is required."); return await OnDebuggerAsync(()=>{ var runtime=SelectRuntime(req); var id=objectIds.GetObjectId(runtime,number) ?? throw new RpcException("object_id_not_found",$"Object ID ${number} is not active in the selected runtime."); var info=DescribeObjectId(id,"$"+number,null); objectIds.Remove(id); return info; },cancellationToken).ConfigureAwait(false); }
		static ObjectIdInfo DescribeObjectId(DbgObjectId id,string expression,EvaluatedValue? value)=>new ObjectIdInfo { ObjectId=id.Id,Expression=expression,ProcessId=id.Process.Id,RuntimeId=id.Runtime.Guid.ToString("D"),Value=value };
		void ValidateRuntime(RpcRequest req,DbgRuntime actual) { var process=(int?)req.Arguments["process_id"]; var runtime=(string?)req.Arguments["runtime_id"]; if(process.HasValue && process.Value!=actual.Process.Id) throw new RpcException("target_mismatch","The selected frame is owned by a different process."); if(!string.IsNullOrEmpty(runtime) && !StringComparer.OrdinalIgnoreCase.Equals(runtime,actual.Guid.ToString("D")) && !StringComparer.OrdinalIgnoreCase.Equals(runtime,actual.Name)) throw new RpcException("target_mismatch","The selected frame is owned by a different runtime."); }

		async Task<EvaluatedValue[]> GetAutosAsync(RpcRequest req,CancellationToken cancellationToken) { CheckSession(req); return await WithEvaluationAsync(req,(captured,eval)=>{ ValidateRuntime(req,captured.Frame.Runtime); var nodes=captured.Language.AutosProvider.GetNodes(eval,NodeOptions((bool?)req.Arguments["allow_func_eval"]??false)); try { return nodes.Take(200).Select(n=>DescribeNode(n,eval,n.Expression)).ToArray(); } finally { manager.Close(nodes); } },cancellationToken).ConfigureAwait(false); }

		OutputResult GetOutput(RpcRequest req) { CheckSession(req); return OutputResultOf(output.Snapshot((long?)req.Arguments["after_output_id"]??0)); }
		async Task<WaitOutputResult> WaitForOutputAsync(RpcRequest req,CancellationToken cancellationToken) { CheckSession(req); var after=(long?)req.Arguments["after_output_id"]??0; var timeout=Math.Min(10000,Math.Max(1,(int?)req.Arguments["timeout_ms"]??5000)); using var wait=CancellationTokenSource.CreateLinkedTokenSource(cancellationToken); wait.CancelAfter(timeout); while(true) { var snapshot=output.Snapshot(after); if(snapshot.Messages.Length!=0 || snapshot.Truncated) return WaitOutputResultOf(snapshot,false); try { await output.WaitAsync(snapshot.Last,wait.Token).ConfigureAwait(false); } catch(OperationCanceledException) when(!cancellationToken.IsCancellationRequested) { return WaitOutputResultOf(output.Snapshot(after),true); } } }
		static OutputResult OutputResultOf(OutputSnapshot s)=>new OutputResult { Messages=s.Messages,OldestOutputId=s.Oldest,OldestAvailableCursor=s.Cursor,LastOutputId=s.Last,Truncated=s.Truncated };
		static WaitOutputResult WaitOutputResultOf(OutputSnapshot s,bool timedOut)=>new WaitOutputResult { Messages=s.Messages,OldestOutputId=s.Oldest,OldestAvailableCursor=s.Cursor,LastOutputId=s.Last,Truncated=s.Truncated,TimedOut=timedOut };

		async Task<ModuleBreakpointInfo> SetModuleBreakpointAsync(RpcRequest req,CancellationToken cancellationToken) { CheckSession(req); return await OnDebuggerAsync(()=>Describe(moduleBreakpoints.Add(ModuleSettings(req,new DbgModuleBreakpointSettings { IsEnabled=true }))),cancellationToken).ConfigureAwait(false); }
		async Task<ModuleBreakpointInfo[]> ListModuleBreakpointsAsync(CancellationToken cancellationToken)=>await OnDebuggerAsync(()=>moduleBreakpoints.Breakpoints.Select(Describe).ToArray(),cancellationToken).ConfigureAwait(false);
		async Task<ModuleBreakpointInfo> UpdateModuleBreakpointAsync(RpcRequest req,CancellationToken cancellationToken) { CheckSession(req); return await OnDebuggerAsync(()=>{ var bp=FindModuleBreakpoint(req); bp.Settings=ModuleSettings(req,bp.Settings); return Describe(bp); },cancellationToken).ConfigureAwait(false); }
		async Task<ModuleBreakpointInfo> RemoveModuleBreakpointAsync(RpcRequest req,CancellationToken cancellationToken) { CheckSession(req); return await OnDebuggerAsync(()=>{ var bp=FindModuleBreakpoint(req); var info=Describe(bp); moduleBreakpoints.Remove(bp); return info; },cancellationToken).ConfigureAwait(false); }
		DbgModuleBreakpoint FindModuleBreakpoint(RpcRequest req) { var id=(int?)req.Arguments["breakpoint_id"]??throw new RpcException("invalid_arguments","breakpoint_id is required."); return moduleBreakpoints.Breakpoints.FirstOrDefault(b=>b.Id==id)??throw new RpcException("breakpoint_not_found",$"Module breakpoint {id} was not found."); }
		static DbgModuleBreakpointSettings ModuleSettings(RpcRequest req,DbgModuleBreakpointSettings s) { if(req.Arguments["enabled"] is not null)s.IsEnabled=(bool)req.Arguments["enabled"]!; if(req.Arguments["module_name"] is not null)s.ModuleName=(string?)req.Arguments["module_name"]; if(req.Arguments["is_dynamic"] is not null)s.IsDynamic=(bool?)req.Arguments["is_dynamic"]; if(req.Arguments["is_in_memory"] is not null)s.IsInMemory=(bool?)req.Arguments["is_in_memory"]; if(req.Arguments["is_loaded"] is not null)s.IsLoaded=(bool?)req.Arguments["is_loaded"]; if(req.Arguments["order"] is not null)s.Order=(int?)req.Arguments["order"]; if(req.Arguments["process_name"] is not null)s.ProcessName=(string?)req.Arguments["process_name"]; if(req.Arguments["app_domain_name"] is not null)s.AppDomainName=(string?)req.Arguments["app_domain_name"]; return s; }
		static ModuleBreakpointInfo Describe(DbgModuleBreakpoint b)=>new ModuleBreakpointInfo { BreakpointId=b.Id,Enabled=b.IsEnabled,ModuleName=b.ModuleName,IsDynamic=b.IsDynamic,IsInMemory=b.IsInMemory,IsLoaded=b.IsLoaded,Order=b.Order,ProcessName=b.ProcessName,AppDomainName=b.AppDomainName };

		async Task<ExceptionCategoryInfo[]> ListExceptionCategoriesAsync(CancellationToken token)=>await OnDebuggerAsync(()=>exceptions.CategoryDefinitions.Select(c=>new ExceptionCategoryInfo { Category=c.Name,DisplayName=c.DisplayName }).ToArray(),token).ConfigureAwait(false);
		async Task<ExceptionPolicyInfo[]> ListExceptionPoliciesAsync(RpcRequest req,CancellationToken token) { var max=Math.Min(2000,Math.Max(1,(int?)req.Arguments["count"]??200)); return await OnDebuggerAsync(()=>exceptions.Exceptions.Take(max).Select(e=>Policy(e.Definition,e.Settings)).ToArray(),token).ConfigureAwait(false); }
		async Task<ExceptionPolicyInfo> SetExceptionPolicyAsync(RpcRequest req,CancellationToken token) { var id=ExceptionId(req); return await OnDebuggerAsync(()=>{ var flags=((bool?)req.Arguments["stop_thrown"]??false?DbgExceptionDefinitionFlags.StopFirstChance:0)|((bool?)req.Arguments["stop_unhandled"]??false?DbgExceptionDefinitionFlags.StopSecondChance:0); var conditions=(req.Arguments["conditions"]?.ToObject<ExceptionConditionInfo[]>()??Array.Empty<ExceptionConditionInfo>()).Select(c=>new DbgExceptionConditionSettings(c.Kind=="module_not_equals"?DbgExceptionConditionType.ModuleNameNotEquals:DbgExceptionConditionType.ModuleNameEquals,c.Module)).ToList().AsReadOnly(); var settings=new DbgExceptionSettings(flags,conditions); if(exceptions.TryGetDefinition(id,out var definition)) exceptions.Modify(id,settings); else { definition=new DbgExceptionDefinition(id,DbgExceptionDefinitionFlags.None); exceptions.Add(new DbgExceptionSettingsInfo(definition,settings)); } return Policy(definition,settings); },token).ConfigureAwait(false); }
		async Task<ExceptionPolicyInfo> RemoveExceptionPolicyAsync(RpcRequest req,CancellationToken token) { var id=ExceptionId(req); return await OnDebuggerAsync(()=>{ if(!exceptions.TryGetDefinition(id,out var definition)||!exceptions.TryGetSettings(id,out var settings)) throw new RpcException("exception_policy_not_found",id.ToString()); var info=Policy(definition,settings); exceptions.Remove(new[]{id}); return info; },token).ConfigureAwait(false); }
		async Task<bool> RestoreExceptionDefaultsAsync(CancellationToken token) { await OnDebuggerAsync(()=>{ exceptions.Reset(); return true; },token).ConfigureAwait(false); return await OnDebuggerAsync(()=>true,token).ConfigureAwait(false); }
		static DbgExceptionId ExceptionId(RpcRequest req)=>ExceptionId((string?)req.Arguments["category"]??PredefinedExceptionCategories.DotNet,(string?)req.Arguments["name"]);
		static ExceptionPolicyInfo Policy(DbgExceptionDefinition d,DbgExceptionSettings s)=>new ExceptionPolicyInfo { Category=d.Id.Category,Name=d.Id.Name,StopThrown=(s.Flags&DbgExceptionDefinitionFlags.StopFirstChance)!=0,StopUnhandled=(s.Flags&DbgExceptionDefinitionFlags.StopSecondChance)!=0,Conditions=s.Conditions.Select(c=>new ExceptionConditionInfo { Kind=c.ConditionType==DbgExceptionConditionType.ModuleNameNotEquals?"module_not_equals":"module_equals",Module=c.Condition }).ToArray() };

		async Task<ValueExportChunk> GetValueExportAsync(RpcRequest req,CancellationToken token) { var bytes=await ReadExportBytesAsync(req,token).ConfigureAwait(false); var offset=Math.Max(0,(int?)req.Arguments["offset"]??0); var count=Math.Min(1024*1024,Math.Max(1,(int?)req.Arguments["count"]??262144)); if(offset>bytes.Length) throw new RpcException("invalid_arguments","offset exceeds value size."); var length=Math.Min(count,bytes.Length-offset); var chunk=new byte[length]; Buffer.BlockCopy(bytes,offset,chunk,0,length); return new ValueExportChunk { Expression=(string?)req.Arguments["expression"]??"",Offset=offset,Count=length,TotalSize=bytes.Length,Truncated=offset+length<bytes.Length,Sha256=Hash(bytes),DataBase64=Convert.ToBase64String(chunk) }; }
		async Task<HostExportResult> WriteValueExportAsync(RpcRequest req,CancellationToken token) {
			var bytes=await ReadExportBytesAsync(req,token).ConfigureAwait(false); var configured=Environment.GetEnvironmentVariable("DGSPY_EXPORT_ROOT");
			if(string.IsNullOrWhiteSpace(configured)) throw new RpcException("capability_unavailable","Set DGSPY_EXPORT_ROOT to enable host value export.");
			var root=Path.GetFullPath(configured!); var requested=(string?)req.Arguments["path"]??throw new RpcException("invalid_arguments","path is required."); var path=Path.GetFullPath(Path.IsPathRooted(requested)?requested:Path.Combine(root,requested)); var prefix=root.TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;
			if(!path.StartsWith(prefix,StringComparison.OrdinalIgnoreCase)) throw new RpcException("path_not_allowed","The export path is outside DGSPY_EXPORT_ROOT.");
			RejectReparsePath(root,Path.GetDirectoryName(path)!); if(File.Exists(path)&&!((bool?)req.Arguments["overwrite"]??false)) throw new RpcException("file_exists","The export path already exists; pass overwrite=true explicitly.");
			Directory.CreateDirectory(Path.GetDirectoryName(path)!); File.WriteAllBytes(path,bytes); var audit=AuditMutation(req.Operation,$"path={path} length={bytes.Length} sha256={Hash(bytes)}"); return new HostExportResult { Path=path,Size=bytes.Length,Sha256=Hash(bytes),AuditId=audit };
		}
		static void RejectReparsePath(string root,string directory) { for(var current=new DirectoryInfo(directory);current is not null&&current.FullName.StartsWith(root,StringComparison.OrdinalIgnoreCase);current=current.Parent) if(current.Exists&&(current.Attributes&FileAttributes.ReparsePoint)!=0) throw new RpcException("path_not_allowed","The export path crosses a reparse point."); }
		async Task<byte[]> ReadExportBytesAsync(RpcRequest req,CancellationToken token) { CheckSession(req); var expression=(string?)req.Arguments["expression"]; if(string.IsNullOrWhiteSpace(expression)) throw new RpcException("invalid_arguments","expression is required."); return await WithEvaluationAsync(req,(captured,eval)=>{ ValidateRuntime(req,captured.Frame.Runtime); var nodes=CreateNodes(captured,eval,new[]{expression!},false,false); try { var value=nodes[0].Value??throw new RpcException("value_unavailable",nodes[0].ErrorMessage??"No value."); if(value.HasRawValue) { if(value.RawValue is string text) return System.Text.Encoding.UTF8.GetBytes(text); if(value.RawValue is not null) { using var memory=new MemoryStream(); using(var writer=new BinaryWriter(memory)) { switch(value.RawValue) { case byte v: writer.Write(v); break; case sbyte v: writer.Write(v); break; case short v: writer.Write(v); break; case ushort v: writer.Write(v); break; case int v: writer.Write(v); break; case uint v: writer.Write(v); break; case long v: writer.Write(v); break; case ulong v: writer.Write(v); break; case float v: writer.Write(v); break; case double v: writer.Write(v); break; case bool v: writer.Write(v); break; case char v: writer.Write(v); break; default: throw new RpcException("capability_unavailable","The value has no supported byte representation."); } } return memory.ToArray(); } } var address=value.GetRawAddressValue(true)??throw new RpcException("capability_unavailable","The value exposes neither a scalar nor a raw data address."); if(address.Length>16*1024*1024) throw new RpcException("output_too_large","Value exports are capped at 16 MiB."); return value.Process.ReadMemory(address.Address,(int)address.Length); } finally { manager.Close(nodes); } },token).ConfigureAwait(false); }
		static string Hash(byte[] bytes) { using var sha=SHA256.Create(); return BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-","").ToLowerInvariant(); }
	}
}
